# Generated by Django 4.1.7 on 2023-03-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tier', '0002_subscription_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='title',
            field=models.CharField(default=0, max_length=150, verbose_name='Titile'),
            preserve_default=False,
        ),
    ]
