# Generated by Django 4.1.7 on 2023-04-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tier', '0003_tier_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
    ]
