# Generated by Django 4.1.7 on 2023-03-25 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_alter_product_image_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('file', models.FileField(upload_to='post_image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_image', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
