# Generated by Django 4.1.7 on 2023-03-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
