# Generated by Django 4.1.7 on 2023-03-26 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='user',
        ),
    ]
