# Generated by Django 4.1.7 on 2023-03-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
