# Generated by Django 4.1.7 on 2023-03-26 07:06

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_delete_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.user_shop_file_path, verbose_name='Image'),
        ),
    ]
